name: Validate Binaries Build

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  build:
    name: Validate Binaries Build
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: '16.0.0'

      - name: Build binaries
        run: |
          chmod +x build_all.sh
          ./build_all.sh
